kind: pipeline
type: docker
name: Linux Build

volumes:
  - name: build
    host:
      path: /mnt/Build

platform:
  os: linux

steps:
  - name: Compile Front End Assets
    image: node:17
    commands:
      - npm install
      - export NODE_OPTIONS=--openssl-legacy-provider && npm run prod

  - name: Build Binary Files
    image: electronuserland/builder
    volumes:
      - name: build
        path: /drone/src/out
    commands:
      - apt-get update && apt-get install -y rpm fakeroot
      - npm run make

trigger:
  branch:
    - master
  event:
    - tag
    - custom

---

kind: pipeline
type: exec
name: Apple Build

platform:
  os: darwin

steps:
  - name: Unlock Developer Certificates
    environment:
      KEYCHAIN_PASS:
        from_secret: keychain_pass
      KEYCHAIN_PATH:
        from_secret: keychain_path
    commands:
      - security unlock-keychain -p $KEYCHAIN_PASS $KEYCHAIN_PATH

  - name: Compile Front End Assets
    commands:
      - npm install
      - npm run prod

  - name: Build Binary Files
    environment:
      CI: 1
      APPLE_ID:
        from_secret: apple_id
      APPLE_ID_PASSWORD:
        from_secret: signing_key
    commands:
      - npm run make

  - name: Sign
    environment:
      KEYCHAIN_PATH:
        from_secret: keychain_path
      KEYCHAIN_CERTIFICATE_IDENTIFIER:
        from_secret: keychain_certificate_identifier
    commands:
      - codesign --force --deep --keychain $KEYCHAIN_PATH --sign $KEYCHAIN_CERTIFICATE_IDENTIFIER ./out/make/volt-${DRONE_TAG}-arm64.dmg
      - codesign --force --deep --keychain $KEYCHAIN_PATH --sign $KEYCHAIN_CERTIFICATE_IDENTIFIER ./out/make/volt-${DRONE_TAG}-x64.dmg

  - name: Notarize
    environment:
      APPLE_ID:
        from_secret: apple_id
      APPLE_ID_PASSWORD:
        from_secret: signing_key
    commands:
      - xcrun altool -t osx -f ./out/make/volt-${DRONE_TAG}-arm64.dmg -primary-bundle-id com.dvigne.volt --notarize-app -username $APPLE_ID -p @env:APPLE_ID_PASSWORD
      - xcrun altool -t osx -f ./out/make/volt-${DRONE_TAG}-x64.dmg -primary-bundle-id com.dvigne.volt --notarize-app -username $APPLE_ID -p @env:APPLE_ID_PASSWORD

  - name: Publish Artifacts
    commands:
      - cp -R -v ./out/* /Volumes/Build

trigger:
  branch:
    - master
  event:
    - tag
    - custom

---

kind: pipeline
type: docker
name: Draft Release

volumes:
  - name: artifacts
    host:
      path: /mnt/Build

steps:
    - name: Publish Artifacts
      image: plugins/github-release
      volumes:
        - name: artifacts
          path: /out
      settings:
        draft: true
        api_key:
          from_secret: github_token
        files:
          - /out/make/*/*/*.dmg
          - /out/make/*/*/*.deb
          - /out/make/*/*/*.rpm
      when:
        event: tag

depends_on:
  - Linux Build
  - Apple Build
